CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --rdzv_endpoint 0.0.0.0:10300 --nproc_per_node=1 train_ksd_latent.py \
        --exp baseline_ksd \
        --datadir ~/workspace/dataset/repa/latent_celeb256  \
        --dataset latent_celeb256 \
        --results-dir /research/cbim/medical/qd66/ksd_exp/ \
        --image-size 32 \
        --num-in-channels 4 \
        --num-classes 0 \
        --weight-schedule ict \
        --target-ema-mode adaptive \
        --start-ema 0.95 \
        --scale-mode progressive \
        --start-scales 8 \
        --end-scales 512 \
        --noise-sampler ict \
        --global-batch-size $((24*2)) \
        --epochs $((700*1)) \
        --lr 1e-4 \
        --num-sampling 8 \
        --num-channels 128 \
        --num-head-channels 64 \
        --num-res-blocks 4 \
        --resblock-updown \
        --ict \
        --max-grad-norm 100 \
        --model-type DiT-B/2 \
        --channel-mult 1,2,3,4 \
        --attention-resolutions 16,8 \
        --normalize-matrix statistic/celeb256_stat.npy \
        --use-diffloss \
        --ot-hard \
        --c-by-loss-std \
        --linear-act relu \
        --norm-type rms \
        --projector-dim 2048 \
        --repa-lamb 0.1 \
        --repa-enc-info 4:dinov2-vit-b \
        --repa-relu-margin 0.4 \
        --repa-timesteps generation \
        --denoising-task-rate 0.5 \
        --repa-mapper repa \
        --mar-mapper-num-res-blocks 0 \
        --num-register 0 \
        --freq-type none \
        --ckpt-every 25 \
        --use-rope \
